services:
  robot_and_monitor:
    build:
      context: ../..
      dockerfile: Dockerfile
    volumes:
      - ../../monitor:/monitor
      - ../../custom:/monitor/custom
      - ../common:/demo/common:ro
      - ./config.yaml:/demo/config.yaml:ro
      - ../../output/nav2_compatible_local:/output
    command: >
      /bin/bash -lc
      "source /opt/ros/kilted/setup.bash &&
       python3 /demo/common/robot_simulator.py cmd-velocity-cycle --ros-args -r __node:=nav2_robot &
       python3 /monitor/monitor_node.py --config /demo/config.yaml"
